# Generated by Django 5.2.17 on 2026-09-18 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='订单号')),
                ('title', models.CharField(max_length=128, verbose_name='订单标题')),
                ('shipping_fee', models.IntegerField(default=0, verbose_name='运费(分)')),
                ('discount_total', models.IntegerField(default=0, verbose_name='订单总优惠(分)')),
                ('paid_total', models.IntegerField(default=0, verbose_name='商品实付(分)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField(verbose_name='行号')),
                ('sku', models.CharField(max_length=32, verbose_name='SKU')),
                ('title', models.CharField(max_length=128, verbose_name='商品名')),
                ('list_price', models.IntegerField(verbose_name='标价(分)')),
                ('is_gift', models.BooleanField(default=False, verbose_name='是否赠品')),
                ('gift_value', models.IntegerField(default=0, verbose_name='赠品价值(分)')),
                ('allocated_discount', models.IntegerField(default=0, verbose_name='分摊优惠(分)')),
                ('allocated_paid', models.IntegerField(default=0, verbose_name='实付分摊(分)')),
                ('refunded_amount', models.IntegerField(default=0, verbose_name='累计已退(分)')),
                ('status', models.CharField(choices=[('NORMAL', '正常'), ('LOCKED', '退款中'), ('RETURNED', '已退')], default='NORMAL', max_length=16)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='refunds.order')),
            ],
            options={
                'ordering': ['line_no'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_no', models.CharField(max_length=32, unique=True, verbose_name='退款单号')),
                ('idempotency_key', models.CharField(max_length=64, unique=True, verbose_name='幂等键')),
                ('status', models.CharField(choices=[('PENDING', '待提交'), ('SUCCESS', '退款成功'), ('FAILED', '退款失败'), ('PENDING_VERIFICATION', '待核实')], default='PENDING', max_length=24)),
                ('amount', models.IntegerField(default=0, verbose_name='退款金额(分)')),
                ('shipping_refund', models.IntegerField(default=0, verbose_name='退运费(分)')),
                ('gift_deduction', models.IntegerField(default=0, verbose_name='赠品扣款(分)')),
                ('is_final', models.BooleanField(default=False, verbose_name='是否末次结清')),
                ('reason', models.CharField(blank=True, default='', max_length=256, verbose_name='退款原因')),
                ('gateway_txn', models.CharField(blank=True, default='', max_length=64, verbose_name='支付网关流水')),
                ('calc_trace', models.JSONField(default=dict, verbose_name='计算依据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='refunds.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RefundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CALLBACK', '网关回调'), ('RECHECK', '主动核实'), ('SUBMIT', '提交网关')], max_length=16)),
                ('callback_id', models.CharField(blank=True, default='', max_length=64, verbose_name='回调幂等号')),
                ('payload', models.JSONField(default=dict, verbose_name='报文')),
                ('note', models.CharField(blank=True, default='', max_length=256, verbose_name='处理结果')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='refunds.refund')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RefundLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='本行退款(分)')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_lines', to='refunds.orderline')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='refunds.refund')),
            ],
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.UniqueConstraint(fields=('order', 'line_no'), name='uniq_order_line_no'),
        ),
        migrations.AddConstraint(
            model_name='refundevent',
            constraint=models.UniqueConstraint(condition=models.Q(('callback_id', ''), _negated=True), fields=('refund', 'callback_id'), name='uniq_refund_callback'),
        ),
        migrations.AddConstraint(
            model_name='refundline',
            constraint=models.UniqueConstraint(fields=('refund', 'order_line'), name='uniq_refund_order_line'),
        ),
    ]
