# Generated by Django 5.0.14 on 2026-09-18 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='订单号')),
                ('customer_name', models.CharField(max_length=64, verbose_name='顾客')),
                ('bundle_name', models.CharField(max_length=128, verbose_name='套装名称')),
                ('total_list_cents', models.IntegerField(verbose_name='原价合计(分)')),
                ('discount_cents', models.IntegerField(verbose_name='优惠总额(分)')),
                ('shipping_cents', models.IntegerField(verbose_name='运费(分)')),
                ('paid_cents', models.IntegerField(verbose_name='实付(分)')),
                ('snapshot', models.JSONField(default=dict, verbose_name='下单快照')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField(verbose_name='行号')),
                ('sku', models.CharField(max_length=32, verbose_name='SKU')),
                ('title', models.CharField(max_length=128, verbose_name='商品名')),
                ('unit_price_cents', models.IntegerField(verbose_name='单价(分)')),
                ('qty', models.IntegerField(verbose_name='数量')),
                ('is_gift', models.BooleanField(default=False, verbose_name='赠品')),
                ('list_total_cents', models.IntegerField(verbose_name='行原价(分)')),
                ('weight', models.IntegerField(verbose_name='分摊权重')),
                ('discount_alloc_cents', models.IntegerField(verbose_name='优惠分摊(分)')),
                ('shipping_alloc_cents', models.IntegerField(verbose_name='运费分摊(分)')),
                ('paid_alloc_cents', models.IntegerField(verbose_name='实付分摊(分)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='refunds.order')),
            ],
            options={
                'ordering': ['line_no'],
                'unique_together': {('order', 'line_no')},
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_no', models.CharField(max_length=32, unique=True, verbose_name='退款单号')),
                ('idempotency_key', models.CharField(max_length=64, unique=True, verbose_name='幂等键')),
                ('amount_cents', models.IntegerField(verbose_name='应退金额(分)')),
                ('status', models.CharField(choices=[('PENDING', '待核实'), ('SUCCESS', '退款成功'), ('FAILED', '支付失败')], default='PENDING', max_length=16, verbose_name='状态')),
                ('transaction_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='支付流水号')),
                ('failure_reason', models.CharField(blank=True, default='', max_length=256, verbose_name='失败原因')),
                ('trace', models.JSONField(default=dict, verbose_name='计算依据快照')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完结时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='refunds.order')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True, verbose_name='回调事件号')),
                ('transaction_id', models.CharField(max_length=64, verbose_name='支付流水号')),
                ('gateway_status', models.CharField(max_length=16, verbose_name='网关状态')),
                ('result', models.CharField(choices=[('accepted', '已受理'), ('held', '结果未知-保持待核实'), ('duplicate', '重复回调-幂等忽略'), ('conflict', '状态冲突-已拒绝')], max_length=16, verbose_name='处理结果')),
                ('payload', models.JSONField(default=dict, verbose_name='回调报文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='接收时间')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='refunds.refund')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RefundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='退货数量')),
                ('amount_cents', models.IntegerField(verbose_name='行退款金额(分)')),
                ('calc_detail', models.JSONField(default=dict, verbose_name='行计算依据')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_items', to='refunds.orderitem')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='refunds.refund')),
            ],
            options={
                'ordering': ['order_item__line_no'],
            },
        ),
    ]
